- Media:
    - Jellyfin:
        href: https://jellyfin.zaini.cloud
        description: Media Streaming Server
        icon: jellyfin.png
        siteMonitor: http://172.23.51.30:8096
    - Seerr:
        href: https://seerr.zaini.cloud
        description: Media Request Management
        icon: seerr.png
        siteMonitor: http://172.23.51.30:5055
- Storage and Backups:
    - Nextcloud:
        href: https://nextcloud.zaini.cloud
        description: File Sync & Share
        icon: nextcloud.png
        siteMonitor: http://172.23.51.30:8080
    - Immich:
        href: https://immich.zaini.cloud
        description: Photo & Video Backup
        icon: immich.png
        siteMonitor: http://172.23.51.30:2283
    - Vaultwarden:
        href: https://vaultwarden.zaini.cloud
        description: Password Manager
        icon: vaultwarden.png
        siteMonitor: http://172.23.51.30:8088
- Tools:
    - ConvertX:
        href: https://convertx.zaini.cloud
        description: File Conversion
        icon: convertx.png
        siteMonitor: http://172.23.51.30:3000
    - IT-Tools:
        href: https://it-tools.zaini.cloud
        description: Various Handy Tools
        icon: it-tools.png
        siteMonitor: http://172.23.51.30:8881
    - Yopass:
        href: https://yopass.zaini.cloud
        description: Secret sharing
        icon: yopass.png
        siteMonitor: http://172.23.51.30:8889
    - Neko:
        href: https://neko.zaini.cloud
        description: Virtual Browser
        icon: neko.png
        siteMonitor: http://172.23.51.30:8880
- Media (Local):
    - Jellyfin:
        href: http://172.23.51.30:8096
        description: Media Streaming Server
        icon: jellyfin.png
        siteMonitor: http://172.23.51.30:8096
    - Seerr:
        href: http://172.23.51.30:5055
        description: Media Request Management
        icon: seerr.png
        siteMonitor: http://172.23.51.30:5055
- Storage and Backups (Local):
    - Immich:
        href: http://172.23.51.30:2283
        description: Photo & Video Backup
        icon: immich.png
        siteMonitor: http://172.23.51.30:2283
- Tools (Local):
    - IT-Tools:
        href: http://172.23.51.30:8881
        description: Various Handy Tools
        icon: it-tools.png
        siteMonitor: http://172.23.51.30:8881
    - Neko:
        href: http://172.23.51.30:8880
        description: Virtual Browser
        icon: neko.png
        siteMonitor: http://172.23.51.30:8880
- Stocks:
    - Watchlist:
        widget:
          type: stocks
          provider: finnhub
          cache: 15
          hideErrors: true
          watchlist:
            - VOO
            - VXUS
            - IBIT
            - GOOG
            - NVDA
            - AMZN
            - MSFT
            - PLTR
            - JPM
            - XOM
