- name: Deploys Docker containers - Open WebUI, Traefik, and Gluetun
  hosts: open_webui
  gather_facts: true
  become: true

  tasks:
    - name: Create Docker directory
      ansible.builtin.file:
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0755"
        path: /home/ubuntu/ollama-aws-hybrid
    - name: Copy compose yaml
      ansible.builtin.copy:
        owner: ubuntu
        group: ubuntu
        mode: "0644"
        src: ../docker-compose.yml
        dest: /home/ubuntu/ollama-aws-hybrid/docker-compose.yml
    - name: Create Traefik directory
      ansible.builtin.file:
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0755"
        path: /home/ubuntu/ollama-aws-hybrid/config
    - name: Copy Traefik config
      ansible.builtin.copy:
        owner: ubuntu
        group: ubuntu
        mode: "0644"
        src: ../config/traefik.yml
        dest: /home/ubuntu/ollama-aws-hybrid/config/traefik.yml
    - name: Copy runtime.env
      ansible.builtin.copy:
        owner: ubuntu
        group: ubuntu
        mode: "0600"
        decrypt: true
        src: ./files/runtime.env
        dest: /home/ubuntu/ollama-aws-hybrid/.env
