- name: Verify Open WebUI host prerequisites
  hosts: open_webui
  gather_facts: true

  tasks:
    - name: Show operating system distribution
      ansible.builtin.debug:
        var: ansible_facts["distribution"]
    - name: Gather service facts
      ansible.builtin.service_facts:
    - name: Verify Docker is running and enabled
      ansible.builtin.assert:
        that:
          - ansible_facts.services['docker.service'].state == 'running'
          - ansible_facts.services['docker.service'].status == 'enabled'
        fail_msg: Docker is not running and/or not enabled
    - name: Check Docker Compose version
      ansible.builtin.command:
        cmd: docker compose version
      register: docker_compose_result
      changed_when: false
    - name: Show Docker Compose version
      ansible.builtin.debug:
        var: docker_compose_result.stdout
