---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Documentation:
    - Zaini.Cloud Wiki:
        - abbr: WIKI
          href: https://wiki.zaini.cloud
          icon: mdi-file-document-outline
          description: "What is this stuff?"

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
          icon: youtube.png
          description: " "

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/
          icon: github.png
          description: " "
