---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Zaini.cloud Admin Dashboard
headerStyle: boxed
theme: dark
hideVersion: true
instanceName: admin

background:
  image: https://images.unsplash.com/photo-1637825891028-564f672aa42c
  blur: xl
  brightness: 90
  opacity: 60

cardBlur: sm

layout:
  Management:
    style: column
    rows: 2
    tab: Home
    icon: mdi-auto-fix-#FFFFFF

  Infrastructure:
    style: column
    rows: 2
    tab: Home
    icon: mdi-server-#FFFFFF

  Tools:
    style: column
    rows: 2
    tab: Home
    icon: mdi-tools-#FFFFFF

  Monitoring:
    style: row
    columns: 1
    tab: Home
    icon: mdi-hospital-box-#FFFFFF

  Network:
    style: row
    columns: 1
    tab: Home
    icon: mdi-lan-#FFFFFF

  Arr Suite:
    style: row
    columns: 1
    tab: Home
    icon: mdi-pirate-#FFFFFF

  Management (Local):
    style: column
    rows: 2
    tab: Local
    icon: mdi-auto-fix-#FFFFFF

  Infrastructure (Local):
    style: column
    rows: 2
    tab: Local
    icon: mdi-server-#FFFFFF

  Tools (Local):
    style: column
    rows: 2
    tab: Local
    icon: mdi-tools-#FFFFFF

  IoT and SmartHome:
    style: column
    rows: 2
    tab: Local
    icon: mdi-home-automation-#FFFFFF

  Monitoring (Local):
    style: row
    columns: 2
    tab: Local
    icon: mdi-hospital-box-#FFFFFF

  Network (Local):
    style: row
    columns: 3
    tab: Local
    icon: mdi-lan-#FFFFFF

  Arr Suite (Local):
    style: row
    columns: 1
    tab: Local
    icon: mdi-pirate-#FFFFFF
