services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: ${HOSTNAME}
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${SYNCTHING_DATA}:/var/syncthing
      ## If directory above is not on host machine (e.g. external drive), use the following:
      - ./config:/var/syncthing/config
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
