services:
  server:
    image: docker.gitea.com/gitea:1.25.4
    container_name: gitea
    env_file: .env
    environment:
      - USER_UID=1010
      - USER_GID=1010
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=$GITEA__database__NAME
      - GITEA__database__USER=$GITEA__database__USER
      - GITEA__database__PASSWD=$GITEA__database__PASSWD
    restart: unless-stopped
    networks:
      - gitea
      - traefik-proxy
    volumes:
      - /mnt/nfs/apps/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3331:3000"
      - "2223:22"
    depends_on:
      - db
    labels:
      - traefik.enable=true

      - traefik.http.routers.gitea.rule=Host(`git.${DOMAIN}`)
      - traefik.http.routers.gitea.entrypoints=websecure
      - traefik.http.routers.gitea.tls=true
      - traefik.http.routers.gitea.tls.certresolver=cloudflare

      - traefik.http.routers.gitea-lan.rule=Host(`git.${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.gitea-lan.entrypoints=websecure
      - traefik.http.routers.gitea-lan.tls=true
      - traefik.http.routers.gitea-lan.tls.certresolver=cloudflare

      - traefik.http.services.gitea.loadbalancer.server.port=3000

  db:
    image: docker.io/library/mysql:8
    restart: unless-stopped
    container_name: gitea-db
    env_file: .env
    environment:
      - USER_UID=1010
      - USER_GID=1010
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    networks:
      - gitea
    volumes:
      - /mnt/nfs/apps/gitea/mysql:/var/lib/mysql

networks:
  gitea:
    external: false
  traefik-proxy:
    external: true
