services:
  portainer:
    image: portainer/portainer-ce:sts
    container_name: portainer-ce
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    networks:
      - traefik-proxy
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`portainer.${DOMAIN}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.frontend.tls.certresolver=cloudflare"
      - "traefik.http.services.frontend.loadbalancer.server.port=9000"
      - "traefik.http.routers.frontend-lan.rule=Host(`portainer.${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.frontend-lan.tls=true"

networks:
  traefik-proxy:
    external: true
volumes:
  portainer_data:
