services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "443:443"
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
      TRAEFIK_CERTIFICATESRESOLVERS_CLOUDFLARE_ACME_EMAIL: ${ACME_EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./letsencrypt/acme.json:/var/traefik/certs/acme.json
    networks:
      - traefik-proxy

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./gluetun:/gluetun
    env_file:
      - .env
    networks:
      - traefik-proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.open-webui.rule=Host(`${OPENWEBUI_HOST}`)
      - traefik.http.routers.open-webui.entrypoints=websecure
      - traefik.http.routers.open-webui.tls=true
      - traefik.http.routers.open-webui.tls.certresolver=cloudflare
      - traefik.http.services.open-webui.loadbalancer.server.port=8080

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    network_mode: "service:gluetun"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - "OLLAMA_BASE_URL=http://192.168.1.100:11434" # Points to the ollama service. Must add 'network_mode: host' to environment on local ollama instance to use local ip
      - "WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}"
    depends_on:
      - gluetun

volumes:
  open-webui:

networks:
  traefik-proxy:
    name: traefik-proxy
    driver: bridge
