services:
  mc:
    image: itzg/minecraft-server:latest
    container_name: my-server
    tty: true
    stdin_open: true
    restart: no
    ports:
      - "25565:25565"
    env_file: .env
    environment:
      EULA: "TRUE"
      # VERSION: ${MINECRAFT_VERSION:-LATEST}
      TYPE: ${TYPE}
      CF_API_KEY: ${CF_API_KEY}
      CF_PAGE_URL: ${CF_PAGE_URL}

      # --- EXTRA MODS ---
      # Add slugs or IDs here (separated by commas or spaces)
      # Example adds 'JourneyMap' and 'Mouse Tweaks'
      # CURSEFORGE_FILES: |
        # geckolib
        # aquaculture
        # naturalist

      # --- VANILLA TWEAKS ---
      # Paste your share code from the website here
      # VANILLATWEAKS_SHARECODE: ${VANILLATWEAKS_SHARECODE}
      VANILLATWEAKS_FILE: /config/vanillatweaks-datapacks.json,/config/vanillatweaks-resourcepacks.json
      REMOVE_OLD_VANILLATWEAKS: "TRUE"

      # --- PERFORMANCE & SYSTEM ---
      MEMORY: ${MEMORY}
      USE_AIKAR_FLAGS: ${USE_AIKAR_FLAGS}
      USE_MEOWICE_FLAGS: ${USE_MEOWICE_FLAGS}
      TZ: ${TZ}

      # --- SERVER SETTINGS ---
      MAX_PLAYERS: ${MAX_PLAYERS}
      MOTD: ${MOTD}
      DIFFICULTY: ${DIFFICULTY}
      PVP: ${PVP}
      LEVEL: ${LEVEL}
      ENABLE_WHITELIST: "true"
      SEED: ${SEED}
      OPS: |-
        ${OPERATOR1}
      WHITELIST: |-
        ${OPERATOR1}
        ${USER1}

    volumes:
      - "./data:/data"
      - ./config/vanillatweaks-datapacks.json:/config/vanillatweaks-datapacks.json:ro
      - ./config/vanillatweaks-resourcepacks.json:/config/vanillatweaks-resourcepacks.json:ro
