daemon=300                              # check every 300 seconds
syslog=yes                              # log update msgs to syslog
#mail=root                              # mail all msgs to root
#mail-failure=root          # mail failed update msgs to root
pid=/var/run/ddclient/ddclient.pid      # record PID in file.
ssl=yes                                 # use ssl-support.  Works with
#use=ip,                     ip=127.0.0.1       # via static IP's
#use=enp0s5,                     if=eth0                # via interfaces
use=web, web=ipify-ipv4                                 # via web

##
## CloudFlare (www.cloudflare.com)
##
protocol=cloudflare,        \
zone=domain.tld,            \
ttl=1,                      \
login=token,     \ # Only needed if you are using your global API key. If you are using an API token, set it to "token" (without double quotes).
password=cfut_xxxxxxxxxxx             \ # This is either your global API key, or an API token. If you are using an API t>
subdomain.domain.tld
