- Management:
    - Portainer:
        href: "https://portainer.{{HOMEPAGE_VAR_DOMAIN}}"
        description: Container Management
        icon: portainer.png
        siteMonitor: "https://{{HOMEPAGE_VAR_APP_HOST}}:9443"
- Infrastructure:
    - Truenas Web-UI:
        href: "https://truenas.{{HOMEPAGE_VAR_DOMAIN}}"
        description: TrueNAS Storage Management
        icon: truenas-scale.png
        siteMonitor: "http://{{HOMEPAGE_VAR_STORAGE_HOST}}:80"
- Tools:
    - Gitea:
        href: "https://git.{{HOMEPAGE_VAR_DOMAIN}}"
        description: Local Git Server
        icon: gitea.png
        siteMonitor: "http://{{HOMEPAGE_VAR_APP_HOST}}:3331"
- Arr Suite:
    - Prowlarr:
        href: "https://prowlarr.{{HOMEPAGE_VAR_DOMAIN}}"
        description: Indexer Manager
        icon: prowlarr.png
        siteMonitor: "http://{{HOMEPAGE_VAR_APP_HOST}}:9696"
    - Lidarr:
        href: "https://lidarr.{{HOMEPAGE_VAR_DOMAIN}}"
        description: Music Automation
        icon: lidarr.png
        siteMonitor: "http://{{HOMEPAGE_VAR_APP_HOST}}:8686"
    - Bazarr:
        href: "https://bazarr.{{HOMEPAGE_VAR_DOMAIN}}"
        description: Subtitle Automation
        icon: bazarr.png
        siteMonitor: "http://{{HOMEPAGE_VAR_APP_HOST}}:6767"
    - Radarr:
        href: "https://radarr.{{HOMEPAGE_VAR_DOMAIN}}"
        description: Movie Automation
        icon: radarr.png
        siteMonitor: "http://{{HOMEPAGE_VAR_APP_HOST}}:7878"
    - Sonarr:
        href: "https://sonarr.{{HOMEPAGE_VAR_DOMAIN}}"
        description: TV Show Automation
        icon: sonarr.png
        siteMonitor: "http://{{HOMEPAGE_VAR_APP_HOST}}:8989"
    - qBittorrent:
        href: "https://qb.{{HOMEPAGE_VAR_DOMAIN}}"
        description: Torrent Client
        icon: qbittorrent.png
        siteMonitor: "http://{{HOMEPAGE_VAR_APP_HOST}}:8122"
        widget:
          type: qbittorrent
          url: "http://{{HOMEPAGE_VAR_APP_HOST}}:8122"
          username: "{{HOMEPAGE_VAR_QBIT_USER}}"
          password: "{{HOMEPAGE_VAR_QBIT_PWD}}"
- Monitoring:
    - Grafana:
        href: "https://grafana.{{HOMEPAGE_VAR_DOMAIN}}"
        description: Metrics & Visualization
        icon: grafana.png
        siteMonitor: "http://{{HOMEPAGE_VAR_MONITOR_HOST}}:3000"
    - Uptime Kuma:
        href: "https://uptime.{{HOMEPAGE_VAR_DOMAIN}}"
        description: Uptime Monitoring
        icon: uptime-kuma.png
        siteMonitor: "http://{{HOMEPAGE_VAR_MONITOR_HOST}}:3001"
        widget:
          type: uptimekuma
          url: "http://{{HOMEPAGE_VAR_MONITOR_HOST}}:3001"
          slug: apps
- Network:
    - UDR7 Router:
        href: https://account.ui.com
        description: Remote Site Management
        icon: ubiquiti.png
        ping: "http://{{HOMEPAGE_VAR_ROUTER_HOST}}"

- Management (Local):
    - Portainer:
        href: "https://{{HOMEPAGE_VAR_APP_HOST}}:9443"
        description: Container Management
        icon: portainer.png
        siteMonitor: "https://{{HOMEPAGE_VAR_APP_HOST}}:9443"
- Infrastructure (Local):
    - Proxmox VE:
        href: "https://{{HOMEPAGE_VAR_PROXMOX_HOST}}:8006"
        description: Virtualization Platform
        icon: proxmox.png
        siteMonitor: "https://{{HOMEPAGE_VAR_PROXMOX_HOST}}:8006"
    - Truenas Web-UI:
        href: "https://{{HOMEPAGE_VAR_STORAGE_HOST}}"
        description: TrueNAS Storage Management
        icon: truenas-scale.png
        siteMonitor: "http://{{HOMEPAGE_VAR_STORAGE_HOST}}:80"
    - Supermicro IPMI Web-UI:
        href: "http://{{HOMEPAGE_VAR_IPMI_HOST}}"
        description: Server Remote Management
        icon: supermicro.png
        ping: "http://{{HOMEPAGE_VAR_IPMI_HOST}}"
- Tools (Local):
    - Syncthing - TrueNAS:
        href: "http://{{HOMEPAGE_VAR_STORAGE_HOST}}:8384"
        description: File Sync
        icon: syncthing.png
        siteMonitor: "http://{{HOMEPAGE_VAR_STORAGE_HOST}}:8384"
- IoT and SmartHome:
    - Home Assistant:
        href: "http://{{HOMEPAGE_VAR_APP_HOST}}:8123"
        description: Home Automation
        icon: home-assistant.png
        siteMonitor: "http://{{HOMEPAGE_VAR_APP_HOST}}:8123"
    - SLZB Web UI:
        href: "http://{{HOMEPAGE_VAR_ZIGBEE_HOST}}:80"
        description: Zigbee Coordinator
        icon: sh-zigbee
- Arr Suite (Local):
    - Prowlarr:
        href: "http://{{HOMEPAGE_VAR_APP_HOST}}:9696"
        description: Indexer Manager
        icon: prowlarr.png
        siteMonitor: "http://{{HOMEPAGE_VAR_APP_HOST}}:9696"
    - Lidarr:
        href: "http://{{HOMEPAGE_VAR_APP_HOST}}:8686"
        description: Music Automation
        icon: lidarr.png
        siteMonitor: "http://{{HOMEPAGE_VAR_APP_HOST}}:8686"
    - Bazarr:
        href: "http://{{HOMEPAGE_VAR_APP_HOST}}:6767"
        description: Subtitle Management
        icon: bazarr.png
        siteMonitor: "http://{{HOMEPAGE_VAR_APP_HOST}}:6767"
    - Radarr:
        href: "http://{{HOMEPAGE_VAR_APP_HOST}}:7878"
        description: Movie Automation
        icon: radarr.png
        siteMonitor: "http://{{HOMEPAGE_VAR_APP_HOST}}:7878"
    - Sonarr:
        href: "http://{{HOMEPAGE_VAR_APP_HOST}}:8989"
        description: TV Show Automation
        icon: sonarr.png
        siteMonitor: "http://{{HOMEPAGE_VAR_APP_HOST}}:8989"
    - qBittorrent:
        href: "http://{{HOMEPAGE_VAR_APP_HOST}}:8122"
        description: Torrent Client
        icon: qbittorrent.png
        siteMonitor: "http://{{HOMEPAGE_VAR_APP_HOST}}:8122"
        widget:
          type: qbittorrent
          url: "http://{{HOMEPAGE_VAR_APP_HOST}}:8122"
          username: "{{HOMEPAGE_VAR_QBIT_USER}}"
          password: "{{HOMEPAGE_VAR_QBIT_PWD}}"
- Monitoring (Local):
    - Grafana:
        href: "http://{{HOMEPAGE_VAR_MONITOR_HOST}}:3000"
        description: Metrics & Visualization
        icon: grafana.png
        siteMonitor: "http://{{HOMEPAGE_VAR_MONITOR_HOST}}:3000"
    - Prometheus:
        href: "http://{{HOMEPAGE_VAR_MONITOR_HOST}}:9090"
        description: Systems Monitoring
        icon: prometheus.png
        siteMonitor: "http://{{HOMEPAGE_VAR_MONITOR_HOST}}:9090"
    - Uptime Kuma:
        href: "http://{{HOMEPAGE_VAR_MONITOR_HOST}}:3001"
        description: Uptime Monitoring
        icon: uptime-kuma.png
        siteMonitor: "http://{{HOMEPAGE_VAR_MONITOR_HOST}}:3001"
        widget:
          type: uptimekuma
          url: "http://{{HOMEPAGE_VAR_MONITOR_HOST}}:3001"
          slug: apps
- Network (Local):
    - UDR7 Router:
        href: "https://{{HOMEPAGE_VAR_ROUTER_HOST}}"
        description: Router Management
        icon: ubiquiti.png
        ping: "http://{{HOMEPAGE_VAR_ROUTER_HOST}}"
    - Sx3008F Switch:
        href: "https://{{HOMEPAGE_VAR_SWITCH_HOST}}"
        description: Homelab Switch Management
        icon: tp-link.png
        ping: "http://{{HOMEPAGE_VAR_SWITCH_HOST}}"
    - Pi-hole:
        href: "https://{{HOMEPAGE_VAR_MONITOR_HOST}}:4438/admin/login"
        description: Ad Blocker
        icon: pi-hole.png
