services:
  db:
    image: postgres:15-alpine
    container_name: wiki-db
    networks:
      - wiki-net
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    logging:
      driver: none
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    container_name: wiki-js
    networks:
      - wiki-net
      - traefik-proxy
    depends_on:
      - db
    init: true
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    restart: unless-stopped
    ports:
      - "8839:3000"
    labels:
      - traefik.enable=true

      - traefik.http.routers.wiki.rule=Host(`wiki.${DOMAIN}`)
      - traefik.http.routers.wiki.entrypoints=websecure
      - traefik.http.routers.wiki.tls=true
      - traefik.http.routers.wiki.tls.certresolver=cloudflare

      - traefik.http.routers.wiki-lan.rule=Host(`wiki.${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.wiki-lan.entrypoints=websecure
      - traefik.http.routers.wiki-lan.tls=true
      - traefik.http.routers.wiki-lan.tls.certresolver=cloudflare

      - traefik.http.services.wiki.loadbalancer.server.port=3000

volumes:
  db-data:

networks:
  wiki-net:
  traefik-proxy:
    external: true

