services:
  memcached:
    image: memcached
    container_name: memchached
    restart: unless-stopped
    expose:
      - "11211"
    networks:
      - traefik-proxy

  yopass:
    image: jhaals/yopass
    container_name: yopass
    restart: unless-stopped
    ports:
      - "8889:80"
    command: "--memcached=memcached:11211 --port 80"
    networks:
      - traefik-proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.yopass.rule=Host(`yopass.${DOMAIN}`)
      - traefik.http.routers.yopass.entrypoints=websecure
      - traefik.http.routers.yopass.tls=true
      - traefik.http.routers.yopass.tls.certresolver=cloudflare
      - traefik.http.services.yopass.loadbalancer.server.port=80

networks:
  traefik-proxy:
    external: true
