services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - CF_ZONE=$CF_ZONE
      - CF_TOKEN=$CF_TOKEN
    volumes:
      - ./config:/config
